### ISSUE TITLE
after installing Python 2.x python2 is not avalible on the path

### ISSUE THREAD

**Issue by hahn-kev** [MatteoH2O1999/build-and-install-python#234]
I've got an application that needs to use python 2.7 but in the shebang it actually references `python2` and not just python. I was able to work around this by having a second step that just makes the link manually, but it would be great if this was built in. I also noticed that in the case of installing python 2 it links `python3` to that python 2 binary, that could cause a lot of confusing errors.

**Comment by MatteoH2O1999** [comment]
Hello,
thank you for taking the time to open an issue.
Regarding you problem I double checked the code and python 2 does not link to `python3` in this action. If the complete action does it, it's probably a byproduct of [actions/setup-python](https://github.com/actions/setup-python), in which case it is expected behavior as the objective of this action is a complete and transparent replication of the original `setup-python` with the exception of building deprecated versions from source.
As for your other point, AFAIK `setup-python` never linked to `python2`, so in order to be as close as possible to the original action I'd prefer to keep it as it is.

I'm going to close this issue for now, but feel free to answer to this if you feel I missed anything.
